name: Deploy update

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH, update .env and frontend web
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/dot-pablomag/web
            sudo git reset --hard
            sudo git pull
            sudo rm .env
            sudo touch .env
            sudo bash -c "echo APP_PORT=${{ secrets.APP_PORT }} >> .env"
            sudo bash -c "echo REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} >> .env"
            sudo bash -c "echo REACT_APP_IMG_SERVICE_URL=${{ secrets.REACT_APP_IMG_SERVICE_URL }} >> .env"
            sudo yarn install
            sudo yarn sass
            sudo yarn build
            pm2 restart pm2.config.js
