name: Deploy update

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH, update .env and frontend web
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/dot-pablomag/web
            sudo git pull
            sudo npm install --production --unsafe-perm
            sudo npm run build
            sudo npm run sass
            sudo rm .env
            sudo touch .env
            sudo bash -c "echo APP_PORT=${{ secrets.APP_PORT }} >> .env"
            sudo bash -c "echo API_URL=${{ secrets.API_URL }} >> .env"
            sudo bash -c "echo IMG_SERVICE_URL=${{ secrets.IMG_SERVICE_URL }} >> .env"
            pm2 restart pm2.config.js
